language: node_js
node_js:
  - "4.2.2"
env:
  - CXX=g++-4.8
addons:
  postgresql: "9.3"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
  - redis-server
before_install:
  - psql -c 'create database test;' -U postgres
  - 'npm i -g npm@3'
  - 'npm install'
  - mkdir /tmp/.gc
script:
  - 'npm test'
