language: node_js
node_js:
  - "4.2.2"
addons:
  postgresql: "9.3"
  sources:
  - ubuntu-toolchain-r-test
  packages:
  - g++-4.8
services:
  - redis-server
before_install:
  - psql -c 'create database test;' -U postgres
  - 'npm install'
script:
  - 'npm test'
env:
  - CXX=g++-4.8
