module.exports  = { enums: {
    'HOLDING_NOT_FOUND': 'HOLDING_NOT_FOUND',
    'MULTIPLE_HOLDINGS_FOUND': 'MULTIPLE_HOLDINGS_FOUND',
    'UNKNOWN_AMEND': 'UNKNOWN_AMEND',
    'ANNUAL_RETURN_HOLDING_DIFFERENCE': 'ANNUAL_RETURN_HOLDING_DIFFERENCE',
    'ANNUAL_RETURN_SHARE_COUNT_DIFFERENCE': 'ANNUAL_RETURN_SHARE_COUNT_DIFFERENCE',
    'AMEND_TRANSFER_ORDER': 'AMEND_TRANSFER_ORDER'
}};
