module.exports  = { enums: {
    'HOLDING_NOT_FOUND': 'HOLDING_NOT_FOUND',
    'MULTIPLE_HOLDINGS_FOUND': 'MULTIPLE_HOLDINGS_FOUND',
    'UNKNOWN_AMEND': 'UNKNOWN_AMEND',
    'ANNUAL_RETURN_HOLDING_DIFFERENCE': 'ANNUAL_RETURN_HOLDING_DIFFERENCE',
    'ANNUAL_RETURN_SHARE_COUNT_DIFFERENCE': 'ANNUAL_RETURN_SHARE_COUNT_DIFFERENCE',
    'DIRECTOR_NOT_FOUND': 'DIRECTOR_NOT_FOUND',
    'AMEND_TRANSFER_ORDER': 'AMEND_TRANSFER_ORDER',
    'MULTI_AMEND_TRANSFER_ORDER': 'MULTI_AMEND_TRANSFER_ORDER',
    'ADDRESS_DIFFERENCE': 'ADDRESS_DIFFERENCE'
}};
