module.exports  = { enums: {
    SEED: 'SEED',
    INCORPORATION: 'INCORPORATION',

    ISSUE: 'ISSUE',
    ISSUE_TO: 'ISSUE_TO',

    CONVERSION: 'CONVERSION',
    CONVERSION_TO: 'CONVERSION_TO',

    SUBDIVISION: 'SUBDIVISION',
    SUBDIVISION_TO: 'SUBDIVISION_TO',

    PURCHASE: 'PURCHASE',
    PURCHASE_FROM: 'PURCHASE_FROM',

    REDEMPTION: 'REDEMPTION',
    REDEMPTION_FROM: 'REDEMPTION_FROM',

    ACQUISITION: 'ACQUISITION',
    ACQUISITION_FROM: 'ACQUISITION_FROM',

    CONSOLIDATION: 'CONSOLIDATION',
    CONSOLIDATION_FROM: 'CONSOLIDATION_FROM',

    CANCELLATION: 'CANCELLATION',
    CANCELLATION_FROM: 'CANCELLATION_FROM',

    REISSUE: 'RESISSUE',
    REISSUE_TO: 'REISSUE_TO',

    AMEND: 'AMEND',
    COMPOUND: 'COMPOUND',
    NEW_ALLOCATION: 'NEW_ALLOCATION',
    REMOVE_ALLOCATION: 'REMOVE_ALLOCATION',
    DETAILS: 'DETAILS',
    DETAILS_MASS: 'DETAILS_MASS',
    NAME_CHANGE: 'NAME_CHANGE',
    ADDRESS_CHANGE: 'ADDRESS_CHANGE',
    USER_FIELDS_CHANGE: 'USER_FIELDS_CHANGE',
    HOLDING_CHANGE: 'HOLDING_CHANGE',
    HOLDING_TRANSFER: 'HOLDING_TRANSFER',
    HOLDER_CHANGE: 'HOLDER_CHANGE',

    TRANSFER: 'TRANSFER',
    TRANSFER_TO: 'TRANSFER_TO',
    TRANSFER_FROM: 'TRANSFER_FROM',

    TRANSFER_TO_ACQUISITION: 'TRANSFER_TO_ACQUISITION',
    TRANSFER_FROM_ACQUISITION: 'TRANSFER_FROM_ACQUISITION',

    TRANSFER_TO_REISSUE: 'TRANSFER_TO_RESISSUE',
    TRANSFER_FROM_REISSUE: 'TRANSFER_FROM_REISSUE',

    ANNUAL_RETURN: 'ANNUAL_RETURN',

    NEW_DIRECTOR: 'NEW_DIRECTOR',
    REMOVE_DIRECTOR: 'REMOVE_DIRECTOR',
    UPDATE_DIRECTOR: 'UPDATE_DIRECTOR',


    REGISTER_ENTRY: 'REGISTER_ENTRY',
    CREATE_SHARE_CLASS: 'CREATE_SHARE_CLASS',
    APPLY_SHARE_CLASS: 'APPLY_SHARE_CLASS',
    APPLY_SHARE_CLASSES: 'APPLY_SHARE_CLASSES',

    COMPOUND_REMOVALS: 'COMPOUND_REMOVALS',

    INFERRED_UPDATE_DIRECTOR: 'INFERRED_UPDATE_DIRECTOR',
    INFERRED_HOLDER_CHANGE: 'INFERRED_HOLDER_CHANGE',
    INFERRED_NEW_DIRECTOR: 'INFERRED_NEW_DIRECTOR',
    INFERRED_REMOVE_DIRECTOR: 'INFERRED_REMOVE_DIRECTOR',
    INFERRED_INTRA_ALLOCATION_TRANSFER: 'INFERRED_INTRA_ALLOCATION_TRANSFER',

    HISTORIC_HOLDER_CHANGE: 'HISTORIC_HOLDER_CHANGE',

    UPLOAD_DOCUMENT: 'UPLOAD_DOCUMENT',
    UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
    CREATE_DIRECTORY: 'CREATE_DIRECTORY',

    AMEND_CONSTITUION: 'AMEND_CONSTITUION',
    REVOKE_CONSTITUION: 'REVOKE_CONSTITUION',
    REPLACE_CONSTITUION: 'REPLACE_CONSTITUION',

    REPLACE_SHARE_CLASS: 'REPLACE_SHARE_CLASS',

    UPDATE_SOURCE_DOCUMENTS: 'UPDATE_SOURCE_DOCUMENTS'

}};
